name: flutter_police_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.5
  flutter_secure_storage: ^6.0.0
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  http: ^0.13.4
  lottie: ^1.2.2
  page_transition: ^2.0.5
  timeago: ^3.2.2
  toggle_switch: ^1.4.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/favicon.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
